---
spec/spec_helper_acceptance.rb:
  windows: true
  dependencies:
    - puppetlabs-stdlib
    - puppetlabs-powershell
spec/acceptance/nodesets/centos-59-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-64-x64-pe.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-65-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-10044-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-12042-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  unmanaged: true
