---
spec/spec_helper.rb:
  spec_overrides: "require 'spec_helper_methods'"
  mock_with: ':mocha'
.github/workflows/ci.yml:
  acceptance_tests: false
Gemfile:
  optional:
    ':test':
      - gem: 'mocha'
