name 'opentable-windows_feature'
version '0.0.2'
author 'opentable'
license 'MIT'
summary 'Module that will turn windows features on or off for Windows Server 2008 and above'
project_page 'https://github.com/opentable/puppet-windowsfeature'
dependency    'puppetlabs/stdlib', '>=3.0.0'
dependency    'joshcooper/powershell', '>=0.0.6'
