name 'opentable-windowsfeature'
version '0.0.1'
author 'opentable'
license 'MIT'
summary 'Module that will turn windows features on or off for Windows Server 2008 and above'
project_page 'https://github.com/opentable/puppet-windowsfeature'
dependency    'puppetlabs/stdlib', '>=3.0.0'
